name: kaka_flutter_mp
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your applicaflutter_spinkitflutter_spinkittion.
  # Use with the CupertinoIcons class for iOS style icons.
  # 调用照相机
  image_picker: ^0.4.12
  flutter_spinkit: ^2.1.0
  # 图标库
  cupertino_icons: ^0.1.2  
  # 轮播图
  flutter_swiper: ^1.1.4
  #谷歌地图
  flutter_map: ^0.4.0
  # 获取定位
  location: ^1.4.1
  amap_location: ^0.1.2
  # 请求
  dio: ^1.0.13 
  # 数据存储 暂定
  shared_preferences: ^0.4.3
  # 自动化的源代码生成器
  json_serializable: ^2.0.1
  # 数据库
  sqflite: ^0.13.0+1
  # 文件路径访问
  path_provider: ^0.4.0
  #上拉加载更多
  pull_to_refresh: ^1.1.6
  #微信支付
  fluwx: ^0.5.5
  #支付宝支付
  flutter_alipay: ^0.1.0

dev_dependencies:
  build_runner: ^1.1.1
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
     - assets/images/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
      - family: iconfont  #指定一个字体名
        fonts:
          - asset: assets/fonts/iconfont.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages

  # 轮播图
# flutter_swiper: ^1.1.4
